### ISSUE TITLE
NameError: name 'discr' is not defined

### ISSUE THREAD

**Issue by liuxm0239** [naivety77/gail_atari#1]
Hi, var discr not found while I am trying to run train_ppo.py

![image](https://user-images.githubusercontent.com/8272997/195036154-a92a9540-43f8-41d3-8811-ac1361a9182e.png)

**Comment by yunke-wang** [comment]
> Hi, var discr not found while I am trying to run train_ppo.py
> 
> ![image](https://user-images.githubusercontent.com/8272997/195036154-a92a9540-43f8-41d3-8811-ac1361a9182e.png)

Hi👋Please set args.gail to False in a2c_ppo_acktr/arguments.py. This might solve the problem.

**Comment by liuxm0239** [comment]
Thank you, that works.
